package main

import (
	"fmt"
	"strings"
)

func generateKuzuDDL(dump SchemaDump) {
	fmt.Println("-- GUAC KuzuDB DDL")
	fmt.Println("-- Auto-generated by schemadump")
	fmt.Println()

	// 1. Create Node Tables
	fmt.Println("-- Node Tables")
	for _, node := range dump.Nodes {
		var cols []string

		// Add properties
		for _, prop := range node.Properties {
			// Quote column names to avoid reserved keywords (though less common in Kuzu, good practice)
			// Kuzu syntax: name type
			cols = append(cols, fmt.Sprintf("%s %s", prop.Name, prop.Type))
		}

		// Add PRIMARY KEY
		// Assuming 'id' is always present and is the PK
		cols = append(cols, "PRIMARY KEY (id)")

		fmt.Printf("CREATE NODE TABLE %s (%s);\n", node.Table, strings.Join(cols, ", "))
	}
	fmt.Println()

	// 2. Create Relationship Tables
	fmt.Println("-- Relationship Tables")
	for _, node := range dump.Nodes {
		for _, edge := range node.Edges {
			var cols []string

			// FROM .. TO ..
			cols = append(cols, fmt.Sprintf("FROM %s TO %s", node.Table, edge.ToTable))

			// Add edge properties
			for _, prop := range edge.Properties {
				cols = append(cols, fmt.Sprintf("%s %s", prop.Name, prop.Type))
			}

			// Use the Symbol as the relationship table name
			// "CREATE REL TABLE <name> (FROM <a> TO <b>, ...);"
			fmt.Printf("CREATE REL TABLE %s (%s);\n", edge.Symbol, strings.Join(cols, ", "))
		}
	}
}
