package main

import (
	"fmt"
	"strings"
)

func generateKuzuDDL(dump SchemaDump) {
	fmt.Println("-- GUAC KuzuDB DDL")
	fmt.Println("-- Auto-generated by schemadump")
	fmt.Println()

	var nodeSummaries []string
	var nodeDefinitions []string
	var edgeSummaries []string
	var edgeDefinitions []string

	// 1. Process Node Tables
	for _, node := range dump.Nodes {
		var cols []string
		var compactCols []string

		for _, prop := range node.Properties {
			cols = append(cols, fmt.Sprintf("    %s %s", prop.Name, prop.Type))
			compactCols = append(compactCols, fmt.Sprintf("%s %s", prop.Name, prop.Type))
		}

		cols = append(cols, "    PRIMARY KEY (id)")
		compactCols = append(compactCols, "PRIMARY KEY (id)")

		nodeSummaries = append(nodeSummaries, fmt.Sprintf("-- CREATE NODE TABLE %s (%s);", node.Table, strings.Join(compactCols, ", ")))
		nodeDefinitions = append(nodeDefinitions, fmt.Sprintf("CREATE NODE TABLE %s (\n%s\n);", node.Table, strings.Join(cols, ",\n")))
	}

	// 2. Process Relationship Tables
	for _, node := range dump.Nodes {
		for _, edge := range node.Edges {
			var cols []string
			var compactCols []string

			cols = append(cols, fmt.Sprintf("    FROM %s TO %s", node.Table, edge.ToTable))
			compactCols = append(compactCols, fmt.Sprintf("FROM %s TO %s", node.Table, edge.ToTable))

			for _, prop := range edge.Properties {
				cols = append(cols, fmt.Sprintf("    %s %s", prop.Name, prop.Type))
				compactCols = append(compactCols, fmt.Sprintf("%s %s", prop.Name, prop.Type))
			}

			edgeSummaries = append(edgeSummaries, fmt.Sprintf("-- CREATE REL TABLE %s (%s);", edge.Symbol, strings.Join(compactCols, ", ")))
			edgeDefinitions = append(edgeDefinitions, fmt.Sprintf("CREATE REL TABLE %s (\n%s\n);", edge.Symbol, strings.Join(cols, ",\n")))
		}
	}

	// Output Table of Contents
	fmt.Println("-- TABLE OF CONTENTS (Schema Summary)")
	fmt.Println("-- Node Tables:")
	for _, s := range nodeSummaries {
		fmt.Println(s)
	}
	fmt.Println("-- Relationship Tables:")
	for _, s := range edgeSummaries {
		fmt.Println(s)
	}
	fmt.Println()

	// Output Full Definitions
	fmt.Println("-- NODE TABLE DEFINITIONS")
	for _, d := range nodeDefinitions {
		fmt.Println(d)
		fmt.Println()
	}

	fmt.Println("-- RELATIONSHIP TABLE DEFINITIONS")
	for _, d := range edgeDefinitions {
		fmt.Println(d)
		fmt.Println()
	}
}
